apiVersion: v1
kind: Service
metadata:
  name: svc-backend
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  selector:
    app: back
  ports:
  - port: 8000
    targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
       app: back
    spec:
      containers:
      - name: back
        image: 922805825674.dkr.ecr.ap-northeast-2.amazonaws.com/web-back:1
        ports:
        - containerPort: 8000
